export { MagicTextEditor } from './components/MagicTextEditor'
export { Toolbar, ToolbarButton, ToolbarDivider, VariableDropdown, TTSPopover } from './components/Toolbar'
export { TTSMarkExtension } from './extensions/TTSMarkExtension'
export type { MagicTextEditorProps, JSONContent, ContentType, Variable, Translations, PartialTranslations, TTSCharacter } from './types'
export { registerLocale, resolveTranslations, useTranslations, en, es } from './i18n'
import './styles/editor.css'
